### ISSUE TITLE
Link in README

### ISSUE THREAD

**Issue by bastelflp** [fiji/bUnwarpJ#3]
The given link for further details in the [README.md](https://github.com/fiji/bUnwarpJ/blob/664f73abfd040cfc9a58dfa9fa009f683135852c/README.md) to [http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ/ ](http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ/) redirects to the main homepage [https://sites.google.com/site/iargandacarreras/](https://sites.google.com/site/iargandacarreras/).

**Comment by ctrueden** [comment]
I see this was updated in a2596cdb92aee5e04b8b459d68389f5c55d2b57d. It is a good idea to cross-link issues with commits. You can even write "Closes #3" in the commit message and GitHub will auto-close the mentioned issue.

Note that the `imagej.net` server does not yet support https—though we are actively working on it. (I know that you could not test this link right now, due to the wiki being down. Sorry about that.)

**Comment by iarganda** [comment]
Aha! Thanks a lot, @ctrueden
